title: My WildCat Studios Portfolio
description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://cm1393829.github.io" 
theme: jekyll-theme-hacker
